name: Windows
on:
  push:
  workflow_dispatch:
    inputs:
      my_value:
        description: 'My input value'
        required: true
        default: 'input test'
        type: string
env:
  MY_VALUE: ${{ github.event.inputs.my_value }}
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: ./install-frp.ps1
      
      - name: run frpc [my_value $MY_VALUE]
        env:
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
        run: ./run-frpc.ps1
