name: Windows-last
on:
  workflow_dispatch:
    inputs:
      remote_port:
        description: 'remote port'
        required: true
        default: '6000'
        type: string
      my_value:
        description: 'My input value'
        required: true
        default: 'input test'
        type: string
env:
  MY_VALUE: ${{ github.event.inputs.my_value }}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $MY_VALUE
      - run: ./install-frp.ps1
      - run: ./install-meta2ctrl.ps1
      #- run: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe ./shurufa.ps1
      - run: powershell ./shurufa.ps1
      - run: powershell ./install-pac.ps1
      - name: run frpc [${{ github.event.inputs.my_value }}]
        env:
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
        run: ./run-frpc.ps1
