name: Windows-last
on:
  workflow_dispatch:
    inputs:
      remote_port:
        description: 'Remote port'
        required: true
        default: '6000'
        type: string
        
      install_package:
        description: 'Need install Apps?'
        required: true
        default: false
        type: boolean
        
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: ./install-frp.ps1
      - run: ./install-meta2ctrl.ps1
      - run: powershell ./shurufa.ps1
      
      - name: install Apps
        if: ${{ github.event.inputs.install_package || false }}
        run: powershell ./install-pac.ps1
        
      - name: run frpc
        env:
          REMOTE_PORT: ${{github.event.inputs.remote_port }}
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
        run: ./run-frpc.ps1
